# Generated by Django 4.2.2 on 2026-01-04 23:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('maths', 'maths'), ('physics', 'physics'), ('english', 'english')], max_length=100)),
                ('time_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('ended', models.BooleanField(default=False)),
                ('question_map', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('pattern', 'pattern'), ('mcq', 'mcq')], max_length=7)),
                ('expected_answer', models.CharField(max_length=4)),
                ('course', models.CharField(choices=[('maths', 'maths'), ('physics', 'physics'), ('english', 'english')], max_length=100)),
                ('option_a', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_scored', models.DateTimeField(blank=True, null=True)),
                ('already_scored', models.BooleanField(default=False)),
                ('final_score', models.FloatField(default=0)),
                ('selected_answers_map', models.JSONField(blank=True, null=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
    ]
