# Generated by Django 4.2.2 on 2026-01-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('ended', False)), fields=('course', 'initiated_by'), name='just_one_active_exam_per_course_per_student'),
        ),
    ]
